# Supabase CLI configuration
project_id = "vvclhzfyszqxvsldkxzq"

[api]
enabled = true
port = 54321

[db]
port = 54322
shadow_port = 54320

[studio]
enabled = true
port = 54323

[ingest]
enabled = false

[storage]
enabled = true
file_size_limit = "5 MiB"
image_transformation_enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600

[functions]
enabled = false
